name: Build

on:
 push:
    branches: [ main ]
 pull_request:
    branches: [ main ]

jobs:
 build:
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v2

    - name: Install Command Line Tools for Xcode (if it's not installed)
      run: |
         if xcode-select --version >/dev/null 2>&1; then
          echo "Xcode Command Line Tools is installed, skipping."
         else
          echo "Xcode Command Line Tools is not installed, installing."
          xcode-select --install
         fi

    - name: Build
      run: |
        xcodebuild build -project Mythic.xcodeproj -scheme Mythic -sdk macosx -skipMacroValidation -skipPackagePluginValidation CODE_SIGNING_ALLOWED=NO
      # can do [xcodebuild -scheme Mythic CODE_SIGNING_ALLOWED=NO], but it's better to be more specific
