name: Build

on:
 push:
    branches: [ main ]
 pull_request:
    branches: [ main ]

jobs:
 build:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        path: repo

    - name: Install Command Line Tools for Xcode (if it's not installed)
      run: |
         if command -v xcode-select &> /dev/null then
          xcode-select --install
         fi

    - name: Build
      run: |
        cd repo
        xcodebuild build -project Mythic.xcodeproj -scheme Mythic -sdk macosx CODE_SIGNING_ALLOWED=NO
      # can do [xcodebuild -scheme Mythic CODE_SIGNING_ALLOWED=NO], but it's better to be more specific
